[package]
name = "C2RustAgent"
version = "0.1.0"
edition = "2024"

[dependencies]
clang = "2.0"
clang-sys = "1.8"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
